## Building the Perceptron

There's not much except a skeleton in this notebook. Most of the content is in the lecture itself as we write the code.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Dataset

df = pd.DataFrame()
df["item"] = ["eggs", "flour", "cheese", "candy", "truffles", "sauce",
              "detergent", "bread", "stickers", "ice cream", "cat food"]
df["list"] = [0,1,1,0,0,1,0,0,0,0,1]
df["out"]  = [1,0,1,0,1,1,1,0,1,1,1]
df["fun"]  = [0,0,0,1,1,0,0,0,1,1,0]
df["20"]   = [0,0,0,0,1,0,1,0,0,0,1]
df["5"]    = [1,0,1,0,0,1,0,1,1,0,0]
df["y"]    = [1,-1,1,-1,1,1,1,-1,-1,-1,1]
df

item  list  out  fun  20  5  y
0        eggs     0    1    0   0  1  1
1       flour     1    0    0   0  0 -1
2      cheese     1    1    0   0  1  1
3       candy     0    0    1   0  0 -1
4    truffles     0    1    1   1  0  1
5       sauce     1    1    0   0  1  1
6   detergent     0    1    0   1  0  1
7       bread     0    0    0   0  1 -1
8    stickers     0    1    1   0  1 -1
9   ice cream     0    1    1   0  0 -1
10   cat food     1    1    0   1  0  1

In [ ]:
def predict(f, w, b):

    a = (b + sum(f*w)) # TODO: Calculate the activation, "a"

    # TODO: set a value of yhat depending on whether a is positive or negative
    if (a >= 0):
        yhat = 1 # TODO
    else:
        yhat = -1 # TODO

    return yhat

In [ ]:
# Initialize the weights and bias to 0 before the loop
w = np.array([0,0,0,0,0])
b = 0

#Code to test our prediction function (this is just for testing, all we need is the w and b above when we have a sheet o weights)

#f = np.array([0 , 1, 1, 0, 0]) #list of features
#w = np.array([0 , -1, -1, 0, 0]) #list of weights

b = 0 #Bias

#What should our prediction be?

#a should be -1

# yhat should be -1

#b+ sum(f*w) #calculation of a

predict(f,w,b)

NameError: name 'f' is not defined

In [ ]:
for index, row in df.iterrows():
    data = row.tolist()
    # TODO: determine the features, the true value of y
    # use the np.array() function to convert the list of features to a numpy array
    features = np.array(data[1:-1])
    y = data[-1]

    yhat = predict(features, w, b) # TODO: Use predict to find yhat

    if (yhat != y):
        # Correct prediction
        # What do we do here?

        #For w can do 2 things

        #This is the long way

        # for i in range(len(w)):
        #   if features[i] != 0:
        #     w[i] = w[i]+1

        # This is the compact way

        w = w+features*y
        b = b+y



    print(w, b) # Show the updated weights and bias

[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  2 -1  1  0] -1
[ 0  1 -2  1 -1] -2
[ 0  1 -2  1 -1] -2
[ 0  1 -2  1 -1] -2
